### ISSUE TITLE
Anoying error i cant find a fix for

### ISSUE THREAD

**Issue by Snif4asYT** [c6161039/Gamesense-forum#1]
https://prnt.sc/pfSkl0FDAvi9
An error was encountered
Error: Unable to fetch guest information.

**Comment by c6161039** [comment]
u need change forums/cache/cache_config.php
forums/config.php

**Comment by c6161039** [comment]
u can change to https://pan.huanmc.xyz/Longteng/skeet_20220331_210946.sql 
https://pan.huanmc.xyz/Longteng/skeet.rip_20220331_210817.zip
and this

**Comment by c6161039** [comment]
if u have something add my discord Longteng#4898 or telegram @Longteng233

**Comment by c6161039** [comment]
look releases
